- name: Check user Admin present or not
  win_domain_user:
    name: "{{ users }}"
    state: query
  register: check_result

- name: showing result
  debug:
    msg: "{{ check_result.state  }}"
- set_fact:
    result: "{{ check_result.state  }}"

- name : Create user Admin if not present
  win_domain_user:
    name: "{{ users }}"
   # password: NRns@bOFJNyX
    state: "{{ state }}"
    groups: "{{ groups }}"
  when: result == "absent"
   # password: "{{ pass }}"
    
    
#  with_items: "{{ user_details }}"
 # with_items: "{{ pass }}"
 # tags: 
 # - user
  
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
 # tags:
  #- service
