---
- name : User Details
  win_domain_user:
    name: "{{ item }}"
    state: "{{ user_action }}"
    password: "{{ pass }}"
    groups: "{{ group_names }}"
  with_items: "{{ user_names }}"
  tags: 
  - user
    
 
- name: Service Details
  win_service:
    name: "{{ item }}"
    state: "{{ service_action }}"
  with_items: "{{ service_names }}"
  tags:
  - service
