---
- name : User Details
  win_domain_user:
    name: "{{ item }}"
    state: "{{ action }}"
    password: "{{ pass }}"
    groups: "{{ group_names }}"
  with_items: "{{ user_details }}"
  tags: 
  - user
    
 
- name: Service Details
  win_service:
    name: "{{ item.user_name }}"
    state: "{{ item.action }}"
  with_items: "{{ service_details }}"
  tags:
  - service
