---
- name : User Details
  win_domain_user:
    name: "{{ item.user_name }}"
    state: "{{ action }}"
    password: "{{ item.pass }}"
    groups: "{{ item.group_names }}"
 # tags: 
  #- user
    
 
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
  #tags:
  #- service
