---
- name: Ensure user bob is present
  win_user:
    name: bob
    password: B0bP4ssw0rd
    state: present
    groups:
      - DnsAdmins
#- name : User Details
 # win_user:
  #  name: "{{ users }}"
   # state: "{{ state }}"
    #groups: "{{ groups }}"
    #password: "{{ pass }}"
 # tags: 
  #- user
    
 
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
  #tags:
  #- service
