- name: User Details
  win_user:
    name: "{{ users }}"
    state: "{{ state }}"
   # password: "{{ pass }}"
   # groups: "{{ groups }}"
    
#  with_items: "{{ user_details }}"
 # with_items: "{{ pass }}"
 # tags: 
 # - user
  
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
 # tags:
  #- service
