- name: User Details
  win_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
   # groups: "{{ groups }}"
   # state: "{{ action }}"
#  with_items: "{{ user_details }}"
 # with_items: "{{ pass }}"
 # tags: 
 # - user
  
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
 # tags:
  #- service
