---
- name : User Details
  win_domain_user:
    name: "{{ item[0] }}"
    firstname: "{{ item[1] }}"
    surname: "{{ item[2] }}"
    password: "{{ pass }}"
    state: "{{ user_action }}"
    groups: "{{ group_names }}"
    password_expired: yes       #will require the user to change their password at next login
  with_nested: 
  - ['user_names']
  - ['first_names']
  - ['last_names']
  tags: 
  - user
    
 
#- name: Service Details
 # win_service:
  #  name: "{{ item }}"
   # state: "{{ service_action }}"
  #with_items: "{{ service_names }}"
  #tags:
  #- service
