- name: User Details
  win_user:
    name: "{{ item.username }}"
   # password: "{{ password }}"
   # groups: "{{ groups }}"
   # state: "{{ action }}"
  with_items: "{{ users }}"
 # tags: 
 # - user
  
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
 # tags:
  #- service
