- name: User Details
  win_user:
    name: "{{ name }}"
    password: "{{ password }}"
    groups: "{{ groups }}"
    state: "{{ action }}"
  tags: 
  - user
  
- name: Service Details
  win_service:
    name: "{{ name }}"
    state: "{{ action }}"
  tags:
  - service
