---
- name: Ensure user bob is present
  win_domain_user:
    name: bob
    firstname: Bob
    surname: Smith
    company: BobCo
    password: NRns@bOFJNyX
    state: present
    groups:
      - Domain Admins
  
#- name : User Details
 # win_user:
  #  name: "{{ users }}"
   # state: "{{ state }}"
    #groups: "{{ groups }}"
    #password: "{{ pass }}"
 # tags: 
  #- user
    
 
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
  #tags:
  #- service
