---

- name: User Details
  win_domain_user:
    name: "{{ item.login_name }}"
    firstname: "{{ item.first_name }}"
    surname: "{{ item.last_name }}"
    password: "{{ pass }}"
    state: "{{ user_action }}"
    #groups: "{{ group_names }}"
    #password_expired: yes       #will require the user to change their password at next login
  with_items: 
  - "{{ user_names }}"
#  register: output_user
#- name: Save Output
 # win_copy:
  #  content: "{{ config.stdout | replace('\\n', '\n') }}"           
   # dest: "{{ file_path }}/{{ inventory_hostname }}.csv"
  tags: 
  - user
    
    

    
- name: Domain Details
  win_domain_user:
   name: "{{ item.login_name }}"
   firstname: "{{ item.first_name }}"
   surname: "{{ item.last_name }}"
   password: "{{ pass }}"
   state: "{{ user_action }}"
   domain_username: "{{ domain_username }}"
   domain_password: "{{ domain_password }}"
   domain_server: "{{ domain_server }}"
   path: "{{ path }}"
  with_items: 
  - "{{ user_names }}"
  #register: output_domain
  tags: 
  - domain
  
  
- name: Group Details
  win_domain_user:
    name: "{{ item.login_name }}"
    firstname: "{{ item.first_name }}"
    surname: "{{ item.last_name }}"
    #password: "{{ pass }}"
    state: "{{ user_action }}"
    groups: "{{ group_names }}"
    #password_expired: yes       #will require the user to change their password at next login
  with_items: 
  - "{{ user_names }}"
  #register: output_group
  tags: 
  - group
  
  
- name: Password Details
  win_domain_user:
    name: "{{ item.login_name }}"
    firstname: "{{ item.first_name }}"
    surname: "{{ item.last_name }}"
    password: "{{ pass }}"
    state: "{{ user_action }}"
    #groups: "{{ group_names }}"
    password_expired: yes       #will require the user to change their password at next login
  with_items: 
  - "{{ user_names }}"
  #register: output_password
  tags: 
  - password
  
  
- name: Service Details
  win_service:
    name: "{{ item }}"
    state: "{{ service_action }}"
  with_items: "{{ service_names }}"
  #register: output_service
  tags:
  - service
  

  
