---
- name : User Details
  win_domain_user:
    name: "{{ item }}"
    state: "{{ user_action }}"
    password: "{{ pass }}"
    groups: "{{ group_names }}"
    password_expired: yes       #will require the user to change their password at next login
  with_items: "{{ user_names }}"
  tags: 
  - user
    
 
- name: Service Details
  win_service:
    name: "{{ item }}"
    state: "{{ service_action }}"
  with_items: "{{ service_names }}"
  tags:
  - service
