- name: User Details
  win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ action }}"
    groups: "{{ item.groups }}"
  tags: 
  - user
  
- name: Service Details
  win_service:
    name: "{{ item.name }}"
    state: "{{ action }}"
  tags:
  - service
