---
- name : User Details
  win_domain_user:
    name: "{{ users }}"
    state: "{{ state }}"
    password: "{{ pass }}"
    groups: "{{ groups }}"
 # tags: 
  #- user
    
 
#- name: Service Details
 # win_service:
  #  name: "{{ name }}"
   # state: "{{ action }}"
  #tags:
  #- service
